[[BerkeleyDB]]
arch = "aarch64"
git-tree-sha1 = "077c6ffd048a91715588f5d9cd2a9d1efe7f22b3"
libc = "glibc"
os = "linux"

    [[BerkeleyDB.download]]
    sha256 = "fdbbe497c7725a72c0268be916ce10f605f6e49ae535740017b140980a234096"
    url = "https://github.com/JuliaBinaryWrappers/BerkeleyDB_jll.jl/releases/download/BerkeleyDB-v18.1.40+0/BerkeleyDB.v18.1.40.aarch64-linux-gnu.tar.gz"
[[BerkeleyDB]]
arch = "aarch64"
git-tree-sha1 = "905e05cc84c64b158cfec0b81af4e990f13c2168"
libc = "musl"
os = "linux"

    [[BerkeleyDB.download]]
    sha256 = "a8a0749400702072ea2b643486b8a4f445d45499a7148893600e2f7e143d5faa"
    url = "https://github.com/JuliaBinaryWrappers/BerkeleyDB_jll.jl/releases/download/BerkeleyDB-v18.1.40+0/BerkeleyDB.v18.1.40.aarch64-linux-musl.tar.gz"
[[BerkeleyDB]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "51aeccf5a5c4843846f70242f4f13c13102707df"
libc = "glibc"
os = "linux"

    [[BerkeleyDB.download]]
    sha256 = "dd5ce230f2f86a8101f491ad325cac49d0000f0373426d563d3b2bcf98ffc994"
    url = "https://github.com/JuliaBinaryWrappers/BerkeleyDB_jll.jl/releases/download/BerkeleyDB-v18.1.40+0/BerkeleyDB.v18.1.40.armv7l-linux-gnueabihf.tar.gz"
[[BerkeleyDB]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "239dd8f26a5ff7ad7abb355653e0170036f046a3"
libc = "musl"
os = "linux"

    [[BerkeleyDB.download]]
    sha256 = "26c9d302949202fd1719966f10b3bcf7aadf50d709a9f18d11e17b9637633780"
    url = "https://github.com/JuliaBinaryWrappers/BerkeleyDB_jll.jl/releases/download/BerkeleyDB-v18.1.40+0/BerkeleyDB.v18.1.40.armv7l-linux-musleabihf.tar.gz"
[[BerkeleyDB]]
arch = "i686"
git-tree-sha1 = "02cd03c086d652646436897647ce60700beb7117"
libc = "glibc"
os = "linux"

    [[BerkeleyDB.download]]
    sha256 = "5690bceb50b4170a51c4752ac1d02355650e503f0aa90e4a85383b13bcfbe5dc"
    url = "https://github.com/JuliaBinaryWrappers/BerkeleyDB_jll.jl/releases/download/BerkeleyDB-v18.1.40+0/BerkeleyDB.v18.1.40.i686-linux-gnu.tar.gz"
[[BerkeleyDB]]
arch = "i686"
git-tree-sha1 = "2c47d79620924db7d9a7fcf082bab7607abc0e07"
libc = "musl"
os = "linux"

    [[BerkeleyDB.download]]
    sha256 = "945831c7c974a54a1a573121bdd2be083a6c936b94fe1b7eb7c3973ea8d39ae1"
    url = "https://github.com/JuliaBinaryWrappers/BerkeleyDB_jll.jl/releases/download/BerkeleyDB-v18.1.40+0/BerkeleyDB.v18.1.40.i686-linux-musl.tar.gz"
[[BerkeleyDB]]
arch = "powerpc64le"
git-tree-sha1 = "5c083cb52ad0363fc604a0b791054694380ee67f"
libc = "glibc"
os = "linux"

    [[BerkeleyDB.download]]
    sha256 = "66873ec277c676d946d3725f7425e414460ac3fb0939f1b98a3f6e2b675d7e9b"
    url = "https://github.com/JuliaBinaryWrappers/BerkeleyDB_jll.jl/releases/download/BerkeleyDB-v18.1.40+0/BerkeleyDB.v18.1.40.powerpc64le-linux-gnu.tar.gz"
[[BerkeleyDB]]
arch = "x86_64"
git-tree-sha1 = "c7583fba42f17dad1dae67035aaff0d21ae4ad79"
os = "macos"

    [[BerkeleyDB.download]]
    sha256 = "37e013a887d87d4dfadc1d04218de9eb5cf8e587c71dfc7f7a154e8c654ac6d0"
    url = "https://github.com/JuliaBinaryWrappers/BerkeleyDB_jll.jl/releases/download/BerkeleyDB-v18.1.40+0/BerkeleyDB.v18.1.40.x86_64-apple-darwin.tar.gz"
[[BerkeleyDB]]
arch = "x86_64"
git-tree-sha1 = "23f32b19b8e0257ec9d43322d41231533a2def1d"
libc = "glibc"
os = "linux"

    [[BerkeleyDB.download]]
    sha256 = "934d17d9532c4fb84b75126cf46484494f03d3af9830c833e1217f13d1b9f1e6"
    url = "https://github.com/JuliaBinaryWrappers/BerkeleyDB_jll.jl/releases/download/BerkeleyDB-v18.1.40+0/BerkeleyDB.v18.1.40.x86_64-linux-gnu.tar.gz"
[[BerkeleyDB]]
arch = "x86_64"
git-tree-sha1 = "f34864f3a23fe248b798d664dfc2db7f668e05f5"
libc = "musl"
os = "linux"

    [[BerkeleyDB.download]]
    sha256 = "bff3630253ce6fb229c4e3ae4da24bef033e3e8fd1c874d4295d6c94b6b3a879"
    url = "https://github.com/JuliaBinaryWrappers/BerkeleyDB_jll.jl/releases/download/BerkeleyDB-v18.1.40+0/BerkeleyDB.v18.1.40.x86_64-linux-musl.tar.gz"
[[BerkeleyDB]]
arch = "x86_64"
git-tree-sha1 = "4b0921e82e873ad3fde6e07ae9f79f809ce2c175"
os = "freebsd"

    [[BerkeleyDB.download]]
    sha256 = "f18049802c9036431c67434e1fc5dccfa5c1bdba5be8f42589d1b85506891d11"
    url = "https://github.com/JuliaBinaryWrappers/BerkeleyDB_jll.jl/releases/download/BerkeleyDB-v18.1.40+0/BerkeleyDB.v18.1.40.x86_64-unknown-freebsd.tar.gz"
