[[BerkeleyDB]]
arch = "aarch64"
git-tree-sha1 = "969961b00559a963ed8818be38973e245a1e3e08"
os = "macos"

    [[BerkeleyDB.download]]
    sha256 = "cb19f3b7be0d87e5facfd33bbbaa754627147b13108e46c17c085132851b17e9"
    url = "https://github.com/JuliaBinaryWrappers/BerkeleyDB_jll.jl/releases/download/BerkeleyDB-v18.1.41+0/BerkeleyDB.v18.1.41.aarch64-apple-darwin.tar.gz"
[[BerkeleyDB]]
arch = "aarch64"
git-tree-sha1 = "06593302c13ffd0d4a64ffa4e77449602d572308"
libc = "glibc"
os = "linux"

    [[BerkeleyDB.download]]
    sha256 = "d36ec38c057fa416c53d87385e2bf3fe19c52870940905b59ed2e53c12b65084"
    url = "https://github.com/JuliaBinaryWrappers/BerkeleyDB_jll.jl/releases/download/BerkeleyDB-v18.1.41+0/BerkeleyDB.v18.1.41.aarch64-linux-gnu.tar.gz"
[[BerkeleyDB]]
arch = "aarch64"
git-tree-sha1 = "25872e6fe640ffd04c9ceb3d8a0132235be5b068"
libc = "musl"
os = "linux"

    [[BerkeleyDB.download]]
    sha256 = "ca48d96018988647916a28f34df01d4ae033c5438f0635d07e912bbc1a9aa966"
    url = "https://github.com/JuliaBinaryWrappers/BerkeleyDB_jll.jl/releases/download/BerkeleyDB-v18.1.41+0/BerkeleyDB.v18.1.41.aarch64-linux-musl.tar.gz"
[[BerkeleyDB]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "8e156e5dada57a7448feb17841a669c751f1d7fa"
libc = "glibc"
os = "linux"

    [[BerkeleyDB.download]]
    sha256 = "4d131eca32f7467fb5036c27c739c52fdf01a244e2ca81dcf9f4af93170c4d2c"
    url = "https://github.com/JuliaBinaryWrappers/BerkeleyDB_jll.jl/releases/download/BerkeleyDB-v18.1.41+0/BerkeleyDB.v18.1.41.armv6l-linux-gnueabihf.tar.gz"
[[BerkeleyDB]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "667fb119d7061bf2f932797fe787c2832c1774d6"
libc = "musl"
os = "linux"

    [[BerkeleyDB.download]]
    sha256 = "1e3d922dab41da0f63bb363d35706fdd4a310822bb1c2c9e27d6f8ecb92d8824"
    url = "https://github.com/JuliaBinaryWrappers/BerkeleyDB_jll.jl/releases/download/BerkeleyDB-v18.1.41+0/BerkeleyDB.v18.1.41.armv6l-linux-musleabihf.tar.gz"
[[BerkeleyDB]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "5efb8c98fd604047655168483c217cd38a3af578"
libc = "glibc"
os = "linux"

    [[BerkeleyDB.download]]
    sha256 = "e19d50cc12661c0a7386836cbf0a1259506fe7dd561a18711d3dd9ffd6b8ad99"
    url = "https://github.com/JuliaBinaryWrappers/BerkeleyDB_jll.jl/releases/download/BerkeleyDB-v18.1.41+0/BerkeleyDB.v18.1.41.armv7l-linux-gnueabihf.tar.gz"
[[BerkeleyDB]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "e24dbe8eb5f9e85db268ccbf2d53e6371eebf888"
libc = "musl"
os = "linux"

    [[BerkeleyDB.download]]
    sha256 = "5fe5b7e98daf551debbc4454fd62817e44b52de6c2c016136d9a6b14e11297f9"
    url = "https://github.com/JuliaBinaryWrappers/BerkeleyDB_jll.jl/releases/download/BerkeleyDB-v18.1.41+0/BerkeleyDB.v18.1.41.armv7l-linux-musleabihf.tar.gz"
[[BerkeleyDB]]
arch = "i686"
git-tree-sha1 = "0172ab51a7c55143ec7accd808f31ea93e22a3e1"
libc = "glibc"
os = "linux"

    [[BerkeleyDB.download]]
    sha256 = "babca6fa430b45a1489417aff99bd55a04d32870a8b690993b88e53a478ffa7a"
    url = "https://github.com/JuliaBinaryWrappers/BerkeleyDB_jll.jl/releases/download/BerkeleyDB-v18.1.41+0/BerkeleyDB.v18.1.41.i686-linux-gnu.tar.gz"
[[BerkeleyDB]]
arch = "i686"
git-tree-sha1 = "ac2ff70218fd0a72831a1df74b6ba99d52312880"
libc = "musl"
os = "linux"

    [[BerkeleyDB.download]]
    sha256 = "1f318dcc75b55271b1febafed726cf16f5e00f294b7421eb7d7a6aeecdaff30d"
    url = "https://github.com/JuliaBinaryWrappers/BerkeleyDB_jll.jl/releases/download/BerkeleyDB-v18.1.41+0/BerkeleyDB.v18.1.41.i686-linux-musl.tar.gz"
[[BerkeleyDB]]
arch = "powerpc64le"
git-tree-sha1 = "59e0c512dc27212d7ab2a0ab31f19cdda857fb15"
libc = "glibc"
os = "linux"

    [[BerkeleyDB.download]]
    sha256 = "7e4d0c96c438333a77a297972d209ed28d87b6c009fa828345a02bb3e9c70a74"
    url = "https://github.com/JuliaBinaryWrappers/BerkeleyDB_jll.jl/releases/download/BerkeleyDB-v18.1.41+0/BerkeleyDB.v18.1.41.powerpc64le-linux-gnu.tar.gz"
[[BerkeleyDB]]
arch = "x86_64"
git-tree-sha1 = "ee3549f12eb0c7f8b12c7d429b8ba12d29c0ca0a"
os = "macos"

    [[BerkeleyDB.download]]
    sha256 = "2f3756cca4f318fd4c692446280e4ef1be2a25d953073817fa58f985e7e6f703"
    url = "https://github.com/JuliaBinaryWrappers/BerkeleyDB_jll.jl/releases/download/BerkeleyDB-v18.1.41+0/BerkeleyDB.v18.1.41.x86_64-apple-darwin.tar.gz"
[[BerkeleyDB]]
arch = "x86_64"
git-tree-sha1 = "08b3c3852673795f2842f0b285c2eaa324af2a11"
libc = "glibc"
os = "linux"

    [[BerkeleyDB.download]]
    sha256 = "350914d505769f07f0a7521e40c812d8462d8b761a383893a0c0774a3443394a"
    url = "https://github.com/JuliaBinaryWrappers/BerkeleyDB_jll.jl/releases/download/BerkeleyDB-v18.1.41+0/BerkeleyDB.v18.1.41.x86_64-linux-gnu.tar.gz"
[[BerkeleyDB]]
arch = "x86_64"
git-tree-sha1 = "8657b53c4b4807f7ebbc2e5053b86dc6c949662c"
libc = "musl"
os = "linux"

    [[BerkeleyDB.download]]
    sha256 = "21df376a44d17b63e3054603b1cbf795f99d5924e5f734fe73de8d2072da221a"
    url = "https://github.com/JuliaBinaryWrappers/BerkeleyDB_jll.jl/releases/download/BerkeleyDB-v18.1.41+0/BerkeleyDB.v18.1.41.x86_64-linux-musl.tar.gz"
[[BerkeleyDB]]
arch = "x86_64"
git-tree-sha1 = "5c67fe96b757157e50c0dd59480cd7064c4d5f0e"
os = "freebsd"

    [[BerkeleyDB.download]]
    sha256 = "3569f4002f49fe011c95c1e755511d489bad21a23074459651ae1c8966e50d70"
    url = "https://github.com/JuliaBinaryWrappers/BerkeleyDB_jll.jl/releases/download/BerkeleyDB-v18.1.41+0/BerkeleyDB.v18.1.41.x86_64-unknown-freebsd.tar.gz"
